# Generated by Django 2.1.5 on 2019-03-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0010_category_name'),
        ('crowdfunder', '0008_merge_20190319_2046'),
    ]

    operations = [
    ]
